export type Destination = {
  id: string;
  name: string;
  x: number;
  y: number;
  photos: string[];
};

export const destinations: Destination[] = [
  {
    id: "paris",
    name: "Paris",
    x: 465,
    y: 130,
    photos: [
      "/album/paris/paris_1.webp",
      "/album/paris/paris_2.webp",
      "/album/paris/paris_3.webp",
      "/album/paris/paris_4.webp",
      "/album/paris/paris_5.webp",
    ],
  },
  {
    id: "quebec",
    name: "Quebec",
    x: 300,
    y: 130,
    photos: [
      "/album/quebec/1.jpg",
      "/album/quebec/2.jpg",
      "/album/quebec/3.jpg",
      "/album/quebec/4.jpg",
    ],
  },
  {
    id: "chiang_mai",
    name: "Chiang Mai",
    x: 700,
    y: 200,
    photos: [
      "/album/chiang_mai/1.jpg",
      "/album/chiang_mai/2.jpg",
      "/album/chiang_mai/3.jpg",
      "/album/chiang_mai/4.JPG",
    ],
  },
  {
    id: "bali",
    name: "Bali",
    x: 740,
    y: 286,
    photos: [
      "/album/bali/bali_1.webp",
      "/album/bali/bali_2.webp",
      "/album/bali/bali_3.webp",
      "/album/bali/bali_4.webp",
    ],
  },
  {
    id: "bangkok",
    name: "Bangkok",
    x: 705,
    y: 225,
    photos: [
      "/album/bangkok/bangkok_1.webp",
      "/album/bangkok/bangkok_2.webp",
      "/album/bangkok/bangkok_3.webp",
      "/album/bangkok/bangkok_4.webp",
      "/album/bangkok/bangkok_5.webp",
      "/album/bangkok/bangkok_6.webp",
    ],
  },
  {
    id: "bretagne",
    name: "Bretagne",
    x: 455,
    y: 130,
    photos: [
      "/album/bretagne/bretagne_1.webp",
      "/album/bretagne/bretagne_2.webp",
      "/album/bretagne/bretagne_3.webp",
      "/album/bretagne/bretagne_4.webp",
      "/album/bretagne/bretagne_5.webp",
      "/album/bretagne/bretagne_6.webp",
      "/album/bretagne/bretagne_7.webp",
    ],
  },
  {
    id: "cinq_terre",
    name: "Cinq Terre",
    x: 485,
    y: 145,
    photos: [
      "/album/cinq_terre/cinq_terres_1.webp",
      "/album/cinq_terre/cinq_terres_2.webp",
      "/album/cinq_terre/cinq_terres_3.webp",
      "/album/cinq_terre/cinq_terres_4.webp",
      "/album/cinq_terre/cinq_terres_6.webp",
    ],
  },
  {
    id: "crete",
    name: "Crète",
    x: 517,
    y: 165,
    photos: [
      "/album/crete/crete_1.webp",
      "/album/crete/crete_2.webp",
      "/album/crete/crete_3.webp",
      "/album/crete/crete_4.webp",
      "/album/crete/crete_5.webp",
    ],
  },
  {
    id: "florence",
    name: "Florence",
    x: 490,
    y: 145,
    photos: [
      "/album/florence/florence_1.webp",
      "/album/florence/florence_2.webp",
      "/album/florence/florence_3.webp",
    ],
  },
  {
    id: "gili",
    name: "Gili",
    x: 745,
    y: 287,
    photos: [
      "/album/gili/gili_1.webp",
      "/album/gili/gili_2.webp",
      "/album/gili/gili_3.webp",
      "/album/gili/gili_4.webp",
      "/album/gili/gili_5.webp",
    ],
  },
  {
    id: "koh_samui",
    name: "Koh Samui",
    x: 703,
    y: 235,
    photos: [
      "/album/koh_samui/koh_samui_1.webp",
      "/album/koh_samui/koh_samui_2.webp",
      "/album/koh_samui/koh_samui_3.webp",
      "/album/koh_samui/koh_samui_4.webp",
      "/album/koh_samui/koh_samui_5.webp",
    ],
  },
  {
    id: "kuala_lumpur",
    name: "Kuala Lumpur",
    x: 708,
    y: 255,
    photos: [
      "/album/kuala_lumpur/kuala_lumpur_1.webp",
      "/album/kuala_lumpur/kuala_lumpur_2.webp",
      "/album/kuala_lumpur/kuala_lumpur_3.webp",
      "/album/kuala_lumpur/kuala_lumpur_4.webp",
      "/album/kuala_lumpur/kuala_lumpur_5.webp",
      "/album/kuala_lumpur/kuala_lumpur_6.webp",
    ],
  },
  {
    id: "lombok",
    name: "Lombok",
    x: 750,
    y: 287,
    photos: [
      "/album/lombok/lombok_1.webp",
      "/album/lombok/lombok_2.webp",
      "/album/lombok/lombok_3.webp",
      "/album/lombok/lombok_4.webp",
    ],
  },
  {
    id: "malaga",
    name: "Malaga",
    x: 455,
    y: 160,
    photos: [
      "/album/malaga/malaga_1.webp",
      "/album/malaga/malaga_2.webp",
      "/album/malaga/malaga_3.webp",
      "/album/malaga/malaga_4.webp",
    ],
  },
  {
    id: "milan",
    name: "Milan",
    x: 485,
    y: 140,
    photos: [
      "/album/milan/milan_1.webp",
      "/album/milan/milan_2.webp",
      "/album/milan/milan_3.webp",
      "/album/milan/milan_4.webp",
    ],
  },
  {
    id: "nice",
    name: "Nice",
    x: 475,
    y: 143,
    photos: [
      "/album/nice/nice_1.webp",
      "/album/nice/nice_2.webp",
      "/album/nice/nice_3.webp",
      "/album/nice/nice_4.webp",
    ],
  },
  {
    id: "raja_ampat",
    name: "Raja Ampat",
    x: 775,
    y: 265,
    photos: [
      "/album/raja_ampat/raja_ampat_1.webp",
      "/album/raja_ampat/raja_ampat_2.webp",
      "/album/raja_ampat/raja_ampat_3.webp",
      "/album/raja_ampat/raja_ampat_4.webp",
      "/album/raja_ampat/raja_ampat_5.webp",
    ],
  },
  {
    id: "split",
    name: "Split",
    x: 500,
    y: 145,
    photos: [
      "/album/split/Split_1.webp",
      "/album/split/split_2.webp",
      "/album/split/split_3.webp",
      "/album/split/split_4.webp",
      "/album/split/split_5.webp",
      "/album/split/split_6.webp",
    ],
  },
  {
    id: "suisse",
    name: "Suisse",
    x: 485,
    y: 135,
    photos: [
      "/album/suisse/suisse_1.webp",
      "/album/suisse/suisse_2.webp",
      "/album/suisse/suisse_3.webp",
      "/album/suisse/suisse_4.webp",
    ],
  },
  {
    id: "sumbawa",
    name: "Sumbawa",
    x: 755,
    y: 287,
    photos: [
      "/album/sumbawa/sumbawa_1.webp",
      "/album/sumbawa/sumbawa_2.webp",
      "/album/sumbawa/sumbawa_3.webp",
      "/album/sumbawa/sumbawa_4.webp",
      "/album/sumbawa/sumbawa_5.webp",
      "/album/sumbawa/sumbawa_7.webp",
    ],
  },
];